// <auto-generated />
using Luca_Pacinotti_RepositoryEF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Luca_Pacinotti_RepositoryEF.Migrations
{
    [DbContext(typeof(MasterContext))]
    [Migration("20220610103730_PrimaMigrazione")]
    partial class PrimaMigrazione
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Luca_Pacinotti_Core.Entities.Menu", b =>
                {
                    b.Property<int>("IdMenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMenu"), 1L, 1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMenu");

                    b.ToTable("Menu", (string)null);
                });

            modelBuilder.Entity("Luca_Pacinotti_Core.Entities.Piatto", b =>
                {
                    b.Property<int>("IdPiatto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPiatto"), 1L, 1);

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdMenuFK")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPiatto");

                    b.HasIndex("IdMenuFK");

                    b.ToTable("Piatto", (string)null);
                });

            modelBuilder.Entity("Luca_Pacinotti_Core.Entities.Piatto", b =>
                {
                    b.HasOne("Luca_Pacinotti_Core.Entities.Menu", "Menu")
                        .WithMany("Piatto")
                        .HasForeignKey("IdMenuFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Luca_Pacinotti_Core.Entities.Menu", b =>
                {
                    b.Navigation("Piatto");
                });
#pragma warning restore 612, 618
        }
    }
}
